version: '3'

services: 
  web:
    build: .
    volumes:
      - ./auth:/app
    command: |
      sh -c '
      cd /app
      pip install --upgrade pip
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:8000
      '
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cric_backend  # Change 'mydb' to your desired database name
      POSTGRES_USER: postgres  # Change 'myuser' to your desired database user
      POSTGRES_PASSWORD: 1234  # Change 'mypassword' to your desired database password
    ports:
      - 5432:5432  # Expose PostgreSQL port

